### ISSUE TITLE
Contract Wars

### ISSUE THREAD

**Issue by Faalagorn** [aclist/aclist.github.io#19]
Contract Wars is working, it uses Saberclaw anticheat, same as Hired Ops. The game is flee to play.
https://www.contractwarsgame.com/

Installer available at https://lutris.net/games/contract-wars-client/

**Comment by aclist** [comment]
Thank you for the report and apologies for the slow response. This will take a moment to test and include in the list because it is a non-Steam game, but it looks like the install script is straightforward and is only preparing the Wine prefix, not invoking any unorthodox workarounds, so I would tend to agree that this could be considered "out of the box."

**Comment by aclist** [comment]
Resolved per 54d014d
